/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.gestion;

import Model.Producto;
import Model.DAO.GestionInventarioDAO;
import Model.Inventario;
import Model.TpClase;
import Model.TpMarca;
import Model.TpMedida;
import Model.Utils.ActualizarTabla;
import View.Base.MainWindow;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.logging.Logger; // Importar la clase Logger si se va a usar

/**
 *
 * @author Mati
 */
public class AgregarProducto extends javax.swing.JFrame {

    // Se recomienda usar el logger si se comentó en el código anterior
    private static final Logger logger = Logger.getLogger(AgregarProducto.class.getName());
    private final ActualizarTabla actualizarTabla;
    
    private final GestionInventarioDAO gestionInventarioDAO;
    

    /**
     * Creates new form Agregar2
     */
    public AgregarProducto(GestionInventarioDAO gestionInventarioDAO,ActualizarTabla actualizarTabla) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.actualizarTabla = actualizarTabla;
        this.gestionInventarioDAO = gestionInventarioDAO;
        cargarBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jtxt_medida = new javax.swing.JTextField();
        jtxt_nombre = new javax.swing.JTextField();
        jtxt_stock = new javax.swing.JTextField();
        jtxt_precio = new javax.swing.JTextField();
        jcmb_marca = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jcmb_unidadMedida = new javax.swing.JComboBox<>();
        jcmb_clase = new javax.swing.JComboBox<>();
        jtxt_stockCritico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Producto");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Producto"));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Precio:");

        jLabel3.setText("Tipo de Producto:");

        jLabel4.setText("Cantidad");

        jLabel6.setText("Medida:");

        jLabel7.setText("Clase:");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setText("VOLVER");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel8.setText("Marca:");

        jcmb_unidadMedida.addActionListener(this::jcmb_unidadMedidaActionPerformed);

        jcmb_clase.addActionListener(this::jcmb_claseActionPerformed);

        jtxt_stockCritico.addActionListener(this::jtxt_stockCriticoActionPerformed);

        jLabel5.setText("Stock Critico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(83, 83, 83)
                                .addComponent(jtxt_stock))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxt_nombre)
                                    .addComponent(jtxt_precio)
                                    .addComponent(jcmb_unidadMedida, 0, 134, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcmb_marca, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcmb_clase, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxt_medida)
                                    .addComponent(jtxt_stockCritico))))
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcmb_unidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxt_medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcmb_clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmb_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_stockCritico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cargarBoxes(){
        List<TpMarca> listaMarca = gestionInventarioDAO.getMarca();
        List<TpMedida> listaMedida = gestionInventarioDAO.getUnidadMedida();
        List<TpClase> listaClase = gestionInventarioDAO.getClases();
        
        listaMarca.forEach(m->jcmb_marca.addItem(m));
//        TpMarca marcaProducto = listaMarca.stream().filter(m-> m.getCdTpMarca() == prod.getMarca()).findFirst().get();
//        jcmb_marca.setSelectedItem(marcaProducto);
        
        listaMedida.forEach(m->jcmb_unidadMedida.addItem(m));
//        TpMedida medidaProducto = listaMedida.stream().filter(m-> m.getCdTpUnidadMedida()== prod.getTipoProducto()).findFirst().get();
//        jcmb_unidadMedida.setSelectedItem(medidaProducto);
        
        listaClase.forEach(m->jcmb_clase.addItem(m));
//        TpClase claseProducto = listaClase.stream().filter(m-> m.getCdTpClase() == prod.getClase()).findFirst().get();
//        jcmb_clase.setSelectedItem(claseProducto);

        

}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
//            String nombre = jtxt_nombre.getText();
            // Validación básica de números antes de parsear
            if (jtxt_precio.getText().isEmpty() || jtxt_stock.getText().isEmpty() ||
                jtxt_nombre.getText().isEmpty() || jtxt_medida.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos numéricos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            TpMedida medida = (TpMedida)jcmb_unidadMedida.getSelectedItem();
            TpClase clase = (TpClase)jcmb_clase.getSelectedItem();
            TpMarca marca = (TpMarca)jcmb_marca.getSelectedItem();
            
            int precio = Integer.parseInt(jtxt_precio.getText());
//            int tipoProducto = Integer.parseInt(medida.getNmUnidadMedida());
            LocalDateTime fechaExp = LocalDateTime.now();
//            int marca = Integer.parseInt();
            
//            int clase = Integer.parseInt(jTextField3.getText());

            Producto p = new Producto(jtxt_nombre.getText(), precio, medida.getCdTpUnidadMedida(),
                    null, marca.getCdTpMarca(), Integer.parseInt(jtxt_medida.getText()), clase.getCdTpClase());
            GestionInventarioDAO dao = new GestionInventarioDAO();
            
            Inventario inv = new Inventario(0, 0, Integer.parseInt(jtxt_stockCritico.getText()), Integer.parseInt(jtxt_stock.getText()));

            if (dao.agregar(p,inv)) {
                JOptionPane.showMessageDialog(this, "Producto agregado correctamente");
//                JOptionPane.showMessageDialog(this, "Producto agregado correctamente");
//                MainWindow ventana = new MainWindow();
//                ventana.setVisible(true);
                actualizarTabla.reloadTabla(1);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Error al agregar producto", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                this,
                "Error: Asegúrese de que los campos numéricos contengan solo números.",
                "Error de Formato",
                JOptionPane.ERROR_MESSAGE
            );
            logger.severe("Error de formato al ingresar datos: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Error en los datos o base de datos: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            logger.severe("Error al guardar producto: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcmb_unidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_unidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb_unidadMedidaActionPerformed

    private void jcmb_claseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_claseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb_claseActionPerformed

    private void jtxt_stockCriticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_stockCriticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_stockCriticoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//       /* Set the Nimbus look and feel */
//       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//               }
//           }
//       } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//           logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

       /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new AgregarProducto().setVisible(true));
//    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<TpClase> jcmb_clase;
    private javax.swing.JComboBox<TpMarca> jcmb_marca;
    private javax.swing.JComboBox<TpMedida> jcmb_unidadMedida;
    private javax.swing.JTextField jtxt_medida;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_precio;
    private javax.swing.JTextField jtxt_stock;
    private javax.swing.JTextField jtxt_stockCritico;
    // End of variables declaration//GEN-END:variables
}