/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.gestion;

import Model.GetInventario;
import Model.Producto;
import Model.DAO.GestionInventarioDAO;
import Model.Inventario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Puga
 */
public class InventarioVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventarioVista.class.getName());
    
    private final GestionInventarioDAO gestionInventarioDAO;

    /**

     */
    public InventarioVista(GestionInventarioDAO gestionInventarioDAO) {
        this.gestionInventarioDAO = gestionInventarioDAO;
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn_volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtn_agregarProducto = new javax.swing.JButton();
        jbtn_eliminarProducto = new javax.swing.JButton();
        jbtn_modificarProducto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmni_nuevoMarca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtn_volver.setText("Volver");
        jbtn_volver.addActionListener(this::jbtn_volverActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idInventario", "Codigo Producto", "Nombre", "Medida", "Tipo Medida", "Precio", "cantidad", "Eliminado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jbtn_agregarProducto.setText("Agregar Producto");
        jbtn_agregarProducto.addActionListener(this::jbtn_agregarProductoActionPerformed);

        jbtn_eliminarProducto.setText("Eliminar Producto");
        jbtn_eliminarProducto.addActionListener(this::jbtn_eliminarProductoActionPerformed);

        jbtn_modificarProducto.setText("Modificar Producto");
        jbtn_modificarProducto.addActionListener(this::jbtn_modificarProductoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jbtn_agregarProducto)
                .addGap(18, 18, 18)
                .addComponent(jbtn_eliminarProducto)
                .addGap(18, 18, 18)
                .addComponent(jbtn_modificarProducto)
                .addGap(18, 18, 18)
                .addComponent(jbtn_volver)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_agregarProducto)
                    .addComponent(jbtn_eliminarProducto)
                    .addComponent(jbtn_modificarProducto)
                    .addComponent(jbtn_volver))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenu1.setText("Opciones");

        jmni_nuevoMarca.setText("Agregar nueva marca");
        jmni_nuevoMarca.addActionListener(this::jmni_nuevoMarcaActionPerformed);
        jMenu1.add(jmni_nuevoMarca);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_volverActionPerformed

    private void jbtn_modificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_modificarProductoActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un producto para modificar");
        return;
        }
        
        int idInventario = (int) jTable1.getValueAt(fila,0);

        Inventario prodInventario = gestionInventarioDAO.buscarEnInventarioPorId(idInventario);
        System.out.println(prodInventario.toString());
        
        Producto prod = gestionInventarioDAO.findProductoById(prodInventario.getIdProducto());
        System.out.println(prod.toString());
        
        
        ModificarProducto m = new ModificarProducto(prodInventario, prod,new GestionInventarioDAO());
        m.setVisible(true);

        
        
    }//GEN-LAST:event_jbtn_modificarProductoActionPerformed

    private void jbtn_agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarProductoActionPerformed
        // TODO add your handling code here:
        AgregarProducto ventana = new AgregarProducto();
        ventana.setVisible(true);
        
    }//GEN-LAST:event_jbtn_agregarProductoActionPerformed

    private void jbtn_eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarProductoActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un producto para modificar");
        return;
        }
        
        int idProducto = (int) jTable1.getValueAt(fila,1);
        
        if ((boolean)jTable1.getValueAt(fila,7)){
            
            JOptionPane.showMessageDialog(this, "Este producto ya esta eliminado!");
            return;
        }
        
        boolean respuesta = gestionInventarioDAO.expirarProducto(idProducto);
        
        if (!respuesta){
        JOptionPane.showMessageDialog(this,String.format("Error al eliminar", (String) jTable1.getValueAt(fila,2)));
        return;
        }
        JOptionPane.showMessageDialog(this,String.format("Producto %s eliminado", (String) jTable1.getValueAt(fila,2)));
        
        cargarTabla();

        
    }//GEN-LAST:event_jbtn_eliminarProductoActionPerformed

    private void jmni_nuevoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmni_nuevoMarcaActionPerformed
        AgregarMarca m = new AgregarMarca(new GestionInventarioDAO());
        
        m.setVisible(true);
    }//GEN-LAST:event_jmni_nuevoMarcaActionPerformed
    public void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setWidth(0);
        modelo.setRowCount(0);

        GestionInventarioDAO dao = new GestionInventarioDAO();

        for (GetInventario p : dao.listar()) {
            modelo.addRow(new Object[]{
                p.getIdInventario(),
                p.getIdProducto(),
                p.getNmProducto(),
                p.getMedida(),   
                p.getNmMedida(),
                p.getPrecioProducto(),
                p.getStock(),
                p.getLgEliminado()
                
        });
      }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new InventarioVista().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn_agregarProducto;
    private javax.swing.JButton jbtn_eliminarProducto;
    private javax.swing.JButton jbtn_modificarProducto;
    private javax.swing.JButton jbtn_volver;
    private javax.swing.JMenuItem jmni_nuevoMarca;
    // End of variables declaration//GEN-END:variables
}
