/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.gestion;

import Model.Producto;
import Model.DAO.GestionInventarioDAO;
import Model.EliminadoClass;
import Model.Inventario;
import Model.TpClase;
import Model.TpMarca;
import Model.TpMedida;
import java.awt.PopupMenu;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Mati
 */
public class ModificarProducto extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModificarProducto.class.getName());

    private final GestionInventarioDAO gestionInventarioDAO;
    
    private Producto prod;
    private Inventario inv;

    /**
     * Creates new form ModificarProducto
     */

    public ModificarProducto(Inventario inv, Producto prod,GestionInventarioDAO gestionInventarioDAO) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.gestionInventarioDAO = gestionInventarioDAO;
        
        cargarDatos(inv, prod);
        this.inv = inv;
        this.prod = prod;

    }

    private void cargarDatos(Inventario inv, Producto prod) {
        List<TpMarca> listaMarca = gestionInventarioDAO.getMarca();
        List<TpMedida> listaMedida = gestionInventarioDAO.getUnidadMedida();
        List<TpClase> listaClase = gestionInventarioDAO.getClases();
        
        listaMarca.forEach(m->jcmb_marca.addItem(m));
        TpMarca marcaProducto = listaMarca.stream().filter(m-> m.getCdTpMarca() == prod.getMarca()).findFirst().get();
        jcmb_marca.setSelectedItem(marcaProducto);
        
        listaMedida.forEach(m->jcmb_unidadMedida.addItem(m));
        TpMedida medidaProducto = listaMedida.stream().filter(m-> m.getCdTpUnidadMedida()== prod.getTipoProducto()).findFirst().get();
        jcmb_unidadMedida.setSelectedItem(medidaProducto);
        
        listaClase.forEach(m->jcmb_clase.addItem(m));
        TpClase claseProducto = listaClase.stream().filter(m-> m.getCdTpClase() == prod.getClase()).findFirst().get();
        jcmb_clase.setSelectedItem(claseProducto);



        jlbl_nombre.setText(prod.getNombre());
        txtPrecio.setText(String.valueOf(prod.getPrecio()));
        txtMedida.setText(String.valueOf(prod.getMedida()));

        jcmb_eliminado.addItem(new EliminadoClass("Si", true));
        jcmb_eliminado.addItem(new EliminadoClass("No", false));
        jcmb_eliminado.setSelectedIndex(prod.getFechaExpiracion() == null ? 1 : 0);

        jtxt_cantidad.setText(String.valueOf(inv.getStock()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtMedida = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jlbl_nombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxt_cantidad = new javax.swing.JTextField();
        jcmb_eliminado = new javax.swing.JComboBox<>();
        jcmb_marca = new javax.swing.JComboBox<>();
        jcmb_unidadMedida = new javax.swing.JComboBox<>();
        jcmb_clase = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Precio:");

        jLabel3.setText("Clase:");

        jLabel4.setText("Eliminado");

        jLabel5.setText("Marca:");

        jLabel6.setText("Medida:");

        jLabel7.setText("Unidad de Medida:");

        txtMedida.addActionListener(this::txtMedidaActionPerformed);

        btnGuardar.setBackground(new java.awt.Color(0, 255, 0));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setText("VOLVER");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jlbl_nombre.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jlbl_nombre.setText("Nombre Producto");

        jLabel8.setText("Cantidad:");

        jtxt_cantidad.addActionListener(this::jtxt_cantidadActionPerformed);

        jcmb_eliminado.addActionListener(this::jcmb_eliminadoActionPerformed);

        jcmb_unidadMedida.addActionListener(this::jcmb_unidadMedidaActionPerformed);

        jcmb_clase.addActionListener(this::jcmb_claseActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(txtPrecio)
                                    .addComponent(jtxt_cantidad)
                                    .addComponent(jcmb_clase, 0, 95, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMedida)
                                    .addComponent(jcmb_unidadMedida, 0, 95, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcmb_eliminado, 0, 95, Short.MAX_VALUE)
                                    .addComponent(jcmb_marca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlbl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jcmb_eliminado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jcmb_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtxt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcmb_clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(jButton1))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jcmb_unidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            TpClase clase = (TpClase) jcmb_clase.getSelectedItem();
            TpMedida medida = (TpMedida) jcmb_unidadMedida.getSelectedItem();
            TpMarca marca = (TpMarca) jcmb_marca.getSelectedItem();
            EliminadoClass eliminado = (EliminadoClass) jcmb_eliminado.getSelectedItem();
            
Producto p = new Producto(
        this.prod.getIdProducto(),                         
        txtNombre.getText(),                             
        Integer.parseInt(txtPrecio.getText()),            
        medida.getCdTpUnidadMedida(),                      
        eliminado.isValor() ? LocalDateTime.now() : null,  
        marca.getCdTpMarca(),                             
        Integer.parseInt(txtMedida.getText()),            
        clase.getCdTpClase()                               
);

            if (gestionInventarioDAO.actualizar(p)) {
                JOptionPane.showMessageDialog(this, "Producto actualizado con éxito");
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar");
            }
            
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datos inválidos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cantidadActionPerformed

    private void jcmb_eliminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_eliminadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb_eliminadoActionPerformed

    private void txtMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedidaActionPerformed

    private void jcmb_unidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_unidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb_unidadMedidaActionPerformed

    private void jcmb_claseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_claseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb_claseActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//       /* Set the Nimbus look and feel */
//       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//       try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//               if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//               }
//            }
//       } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//       //</editor-fold>
//
//       /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new ModificarProducto().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<TpClase> jcmb_clase;
    private javax.swing.JComboBox<EliminadoClass> jcmb_eliminado;
    private javax.swing.JComboBox<TpMarca> jcmb_marca;
    private javax.swing.JComboBox<TpMedida> jcmb_unidadMedida;
    private javax.swing.JLabel jlbl_nombre;
    private javax.swing.JTextField jtxt_cantidad;
    private javax.swing.JTextField txtMedida;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
