/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Base;

import Model.Utils.ComunicacionInversa;

/**
 *
 * @author vina
 */
public class ConfirmarVenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfirmarVenta.class.getName());
    private final ComunicacionInversa listener;
    private int tpPago;
    /**
     * Creates new form ConfirmarVenta
     */
    public ConfirmarVenta(ComunicacionInversa comunicacionInversa) {
        initComponents();
        this.listener = comunicacionInversa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtng_MetodoPago = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrbtn_credito = new javax.swing.JRadioButton();
        jrbtn_debito = new javax.swing.JRadioButton();
        jbtn_efectivo = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jbtn_guardarVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione Tipo de Pago"));

        jbtng_MetodoPago.add(jrbtn_credito);
        jrbtn_credito.setText("Credito");
        jrbtn_credito.addActionListener(this::jrbtn_creditoActionPerformed);

        jbtng_MetodoPago.add(jrbtn_debito);
        jrbtn_debito.setText("Debito");
        jrbtn_debito.addActionListener(this::jrbtn_debitoActionPerformed);

        jbtng_MetodoPago.add(jbtn_efectivo);
        jbtn_efectivo.setText("Efectivo");
        jbtn_efectivo.addActionListener(this::jbtn_efectivoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jrbtn_credito)
                .addGap(28, 28, 28)
                .addComponent(jrbtn_debito)
                .addGap(37, 37, 37)
                .addComponent(jbtn_efectivo)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtn_credito)
                    .addComponent(jbtn_efectivo)
                    .addComponent(jrbtn_debito))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jButton1.setText("Cancelar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jbtn_guardarVenta.setText("Guardar Venta");
        jbtn_guardarVenta.addActionListener(this::jbtn_guardarVentaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_guardarVenta)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jbtn_guardarVenta))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtn_creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn_creditoActionPerformed
            tpPago = 1;
    }//GEN-LAST:event_jrbtn_creditoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtn_efectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_efectivoActionPerformed
        tpPago = 3;
    }//GEN-LAST:event_jbtn_efectivoActionPerformed

    private void jbtn_guardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarVentaActionPerformed
        listener.tpMetodoPago(tpPago);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_guardarVentaActionPerformed

    private void jrbtn_debitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn_debitoActionPerformed
tpPago = 2;        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtn_debitoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new ConfirmarVenta().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jbtn_efectivo;
    private javax.swing.JButton jbtn_guardarVenta;
    private javax.swing.ButtonGroup jbtng_MetodoPago;
    private javax.swing.JRadioButton jrbtn_credito;
    private javax.swing.JRadioButton jrbtn_debito;
    // End of variables declaration//GEN-END:variables
}
